#!/usr/bin/env bash

function conditional_link() {
    [[ -f $1 ]] \
        && ln -sf $1 $2
}

function run() {
    conditional_link ${CONFIG}/.htpasswd /etc/nginx/.htpasswd
    conditional_link ${CONFIG}/docker-registry.crt /etc/nginx/ssl/docker-registry.crt
    conditional_link ${CONFIG}/docker-registry.key /etc/nginx/ssl/docker-registry.key
    conditional_link ${CONFIG}/docker-registry.yml /etc/docker-registry.yml

    sed -i "s|{{REGISTRY_HOST}}|$REGISTRY_HOST|;s|{{REGISTRY_PORT}}|$REGISTRY_PORT|;s|{{SERVER_NAME}}|$SERVER_NAME|" /etc/nginx/conf.d/default.conf

    /usr/bin/supervisord -n
}

case "$1" in
    cert)
        shift && cd ${CONFIG} && openssl req \
            -new \
            -newkey rsa:4096 \
            -days 365 \
            -nodes \
            -x509 \
            -subj "/C=${C-AU}/ST=${ST-Queensland}/L=${L-Brisbane}/O=${O-Void}/CN=${CN-localhost}" \
            -keyout docker-registry.key \
            -out docker-registry.cert $@ ;;
    htpasswd)
        shift && cd ${CONFIG} && htpasswd ${OPTS--c} .htpasswd $@ ;;
    run|"")
        run ;;
    *)
        echo 1>&2 "Invalid command" ;;
esac
