#!/usr/bin/env bash

function conditional_link() {
    if [ -f $1 ]; then
        ln -sf $1 $2
    fi
}

function conditional_cp() {
    if [ -f $1 ]; then
        rm -rf $2
        cp $1 $2
    fi
}

function conditional_extract() {
    SRC=$1
    DST=${CONFIG}/${2-$(basename ${SRC})}
    if [ -f ${SRC} ] && [ ! -e ${DST} ]; then
        cp -R ${SRC} ${DST}
    fi
}

function extract-config() {
    conditional_extract /etc/nginx/.htpasswd
    conditional_extract ${NGINX_CONFIG} nginx.conf
    conditional_extract ${OPENSSL_CONFIG}
    conditional_extract ${REGISTRY_CERT}
    conditional_extract ${REGISTRY_KEY}
    conditional_extract ${REGISTRY_CONFIG}
}

function pre_run() {
    conditional_cp ${CONFIG}/.htpasswd /etc/nginx/.htpasswd
    conditional_cp ${CONFIG}/$(basename ${REGISTRY_CERT}) ${REGISTRY_CERT}
    conditional_cp ${CONFIG}/$(basename ${REGISTRY_KEY}) ${REGISTRY_KEY}
    conditional_cp ${CONFIG}/nginx.conf ${NGINX_CONFIG}
    conditional_cp ${CONFIG}/openssl.cnf ${OPENSSL_CONFIG}
    conditional_cp ${CONFIG}/$(basename ${REGISTRY_CONFIG}) ${REGISTRY_CONFIG}

    configure_nginx
}

function run() {
    pre_run
    /usr/bin/supervisord -n -c /etc/supervisord.conf
}

function configure_nginx() {
    sed -i "s|{{REGISTRY_HOST}}|$REGISTRY_HOST|;s|{{REGISTRY_PORT}}|$REGISTRY_PORT|;s|{{SERVER_NAME}}|$SERVER_NAME|" ${NGINX_CONFIG}
}

function configure_ssl() {
    sed -i "s|{{SERVER_IP}}|${SERVER_IP}|;s|{{SERVER_NAME}}|${SERVER_NAME}|" ${OPENSSL_CONFIG}
}

function generate_cert() {
    cd ${CONFIG}
    if [ ! -f $(basename ${REGISTRY_CERT}) ] || [ ! -z "${FORCE}"] ; then
        pre_run
        configure_ssl
        openssl req \
            -new \
            -newkey rsa:4096 \
            -days 365 \
            -nodes \
            -x509 \
            -subj "/C=${C-AU}/ST=${ST-Queensland}/L=${L-Brisbane}/O=${O-Void}/CN=${CN-${SERVER_NAME}}" \
            -keyout $(basename ${REGISTRY_KEY}) \
            -out $(basename ${REGISTRY_CERT}) \
            -config ${OPENSSL_CONFIG} $@
    fi
    cd -
}

HTPASSWD_FILE=${CONFIG}/.htpasswd
PASSWORD_FILE=${CONFIG}/.password

function error() {
    echo 1>&2 "[ERROR] Something went wrong; not continuing"
    exit 1
}

function run_htpasswd() {
    [[ ! -f ${HTPASSWD_FILE} ]] && OPTS="${OPTS} -c"
    htpasswd ${OPTS/\w+//} ${HTPASSWD_FILE} $@
}

function setup() {
    cd ${CONFIG}

    generate_cert || error

    if [ -z "${PASSWORD}" ]; then
        if [ ! -f ${PASSWORD_FILE} ]; then
            openssl rand -base64 32 > ${PASSWORD_FILE} || error
            echo "[INFO] PASSWORD=$(cat ${PASSWORD_FILE})"
        fi
        PASSWORD=$(cat ${PASSWORD_FILE})
    fi

    OPTS="${OPTS} -b"
    
    if [ ! -f ${HTPASSWD_FILE} ]; then
        run_htpasswd ${USERNAME-docker} ${PASSWORD} || error
    fi

    extract-config || error

    cd -
}

function usage() {
    cat << EOF

Usage:
 $0 [<command>] [arguments]

Commands:
 gencert    Generate a self-signed certificate. Environment variables respected 
            include: C=AU, ST=Queensland, L=Brisbane, O=Void,CN=\$SERVER_NAME
            NOTE: This will rewrite any pre-existing certificates.

 help       Display this message.
 
 htpasswd   Run htpasswd command to set username/password. Expectes username and
            password (if non-interactive) to be provided. Any additional options 
            to use when generating/modifying ${HTPASSWD_FILE} can be specified 
            using the OPT environment variable.

 setup      Generate SSL cert and htpasswd; and extract all default confiuration
            to ${CONFIG}. When generating htpasswd file the default user docker 
            is used if USERNAME env var is not set; and a random password is 
            generated and stored in ${PASSWORD_FILE} if PASSWORD env var is not 
            set or ${PASSWORD_FILE} is not provided.

 start      (DEFAULT) This command triggers a setup and starts the secure 
            registry. The registry with configuration loaded from ${CONFIG}
            where available or generates initial config before start.
EOF
}

case "$1" in
    gencert)
        shift && export FORCE=1 && generate_cert ;;
    help)
        usage ;;
    htpasswd)
        shift && run_htpasswd $@ ;;
    setup)
        shift && setup ;;
    start|"")
        shift && setup && run ;;
    *)
        echo 1>&2 "Invalid command" ;;
esac
